name: HeritaScan
description: "Effortlessly convert photos to documents with this user-friendly app."

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.1.7
  flutter_pdfview: ^1.4.0
  image: ^4.5.2
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.2
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  pdf: ^3.11.2
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  shared_preferences: ^2.4.0
  lottie: ^3.3.1
  provider: ^6.1.2
  emailjs: ^4.0.0 
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_document_scanner: ^1.1.2
  marquee: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true