name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze || true
