name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze || true
        
      - name: Run tests
        run: flutter test
